# Generated by Django 4.2 on 2023-05-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeastFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
